### ISSUE TITLE
pm2-server-monit: 100% CPU issue

### ISSUE THREAD

**Issue by robin-monnier** [keymetrics/pm2-plus-tech-questions#193]
pm2-server-monit is showing  100% CPU.

Related past problem:
https://github.com/keymetrics/pm2-server-monit/issues/35

#2257

**Comment by karlbecker** [comment]
Another thing I've found is this trace:
```
TypeError: Invalid data, chunk must be a string or buffer, not number
    at TLSSocket.Socket.write (net.js:714:11)
    at ClientRequest._flushOutput (_http_outgoing.js:842:18)
    at ClientRequest._flush (_http_outgoing.js:819:16)
    at ClientRequest._deferToConnect (_http_client.js:277:47)
    at callSocketMethod (_http_client.js:690:7)
    at ClientRequest.onSocket (_http_client.js:695:7)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:121:20)
    at ClientRequest.emit (events.js:211:7)
    at tickOnSocket (_http_client.js:657:7)
```

Any ideas @robin-monnier ?

**Comment by karlbecker** [comment]
We continue to have issues with this, and we are ready to discontinue usage of keymetrics because the false positives of alerts are drowning us.  

We got 87 alerts of high CPU usage in the past 24 hours, which look like this in Slack:
```
Bad behavior
Server: ocelot
Process name: pm2-server-monit
Error message: Probe CPU usage has reached value 90
```

However, these seem to all be false, since our monitoring software for the server shows very low CPU usage over that same amount of time:
<img width="213" alt="screen shot 2018-06-08 at 9 45 14 am" src="https://user-images.githubusercontent.com/1091559/41164375-ad75c940-6b00-11e8-9739-f80991dd4893.png">

Is there any way to reduce the false alarms?  If not, I think we're really going to need to move away from Keymetrics - and we were hoping for accurate alarming to be one of the absolute key features of Keymetrics along with pm2-server-monit.

Thanks for any help you can provide!

**Comment by vmarchaud** [comment]
We released an update that should have fixed the issue
